import { Roboto, Dancing_Script } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { ReactQueryProvider } from "./reactqueyprovider";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "300"],
});
const dancing = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing",
  weight: "400",
});

export const metadata = {
  title: "Anime Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${dancing.variable}`}>
      <body className={`${roboto.variable} font-roboto`}>
        <ReactQueryProvider>
          <Providers>
            <Navbar />
            <main>
              {children}
            </main>
            <Footer />
          </Providers>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
